// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | SocialMediasSlice
  | ListLinkSlice
  | AvatarSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Links Chest field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Share all your links field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *Avatar → Default → Primary*
 */
export interface AvatarSliceDefaultPrimary {
  /**
   * avatar field in *Avatar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: avatar.default.primary.avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * tag name field in *Avatar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: avatar.default.primary.tag_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_name: prismic.KeyTextField;
}

/**
 * Default variation for Avatar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AvatarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AvatarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Avatar*
 */
type AvatarSliceVariation = AvatarSliceDefault;

/**
 * Avatar Shared Slice
 *
 * - **API ID**: `avatar`
 * - **Description**: Avatar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AvatarSlice = prismic.SharedSlice<"avatar", AvatarSliceVariation>;

/**
 * Item in *ListLink → Default → Primary → Links chest*
 */
export interface ListLinkSliceDefaultPrimaryLinksChestItem {
  /**
   * link field in *ListLink → Default → Primary → Links chest*
   *
   * - **Field Type**: Link
   * - **Placeholder**: link to your content
   * - **API ID Path**: list_link.default.primary.links_chest[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ListLink → Default → Primary*
 */
export interface ListLinkSliceDefaultPrimary {
  /**
   * Links chest field in *ListLink → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: list_link.default.primary.links_chest[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links_chest: prismic.GroupField<
    Simplify<ListLinkSliceDefaultPrimaryLinksChestItem>
  >;
}

/**
 * Default variation for ListLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ListLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ListLink*
 */
type ListLinkSliceVariation = ListLinkSliceDefault;

/**
 * ListLink Shared Slice
 *
 * - **API ID**: `list_link`
 * - **Description**: ListLink
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ListLinkSlice = prismic.SharedSlice<
  "list_link",
  ListLinkSliceVariation
>;

/**
 * Item in *SocialMedias → Default → Primary → social medias*
 */
export interface SocialMediasSliceDefaultPrimarySocialMediasItem {
  /**
   * link field in *SocialMedias → Default → Primary → social medias*
   *
   * - **Field Type**: Link
   * - **Placeholder**: link to social media
   * - **API ID Path**: social_medias.default.primary.social_medias[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *SocialMedias → Default → Primary*
 */
export interface SocialMediasSliceDefaultPrimary {
  /**
   * social medias field in *SocialMedias → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_medias.default.primary.social_medias[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_medias: prismic.GroupField<
    Simplify<SocialMediasSliceDefaultPrimarySocialMediasItem>
  >;
}

/**
 * Default variation for SocialMedias Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialMediasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialMediasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialMedias*
 */
type SocialMediasSliceVariation = SocialMediasSliceDefault;

/**
 * SocialMedias Shared Slice
 *
 * - **API ID**: `social_medias`
 * - **Description**: SocialMedias
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialMediasSlice = prismic.SharedSlice<
  "social_medias",
  SocialMediasSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      AvatarSlice,
      AvatarSliceDefaultPrimary,
      AvatarSliceVariation,
      AvatarSliceDefault,
      ListLinkSlice,
      ListLinkSliceDefaultPrimaryLinksChestItem,
      ListLinkSliceDefaultPrimary,
      ListLinkSliceVariation,
      ListLinkSliceDefault,
      SocialMediasSlice,
      SocialMediasSliceDefaultPrimarySocialMediasItem,
      SocialMediasSliceDefaultPrimary,
      SocialMediasSliceVariation,
      SocialMediasSliceDefault,
    };
  }
}
