// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  avatar: dynamic(() => import("./Avatar")),
  list_link: dynamic(() => import("./ListLink")),
  social_medias: dynamic(() => import("./SocialMedias")),
};
